### ISSUE TITLE
ACTIVIDAD 1 Mapa mental

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-1-mapa-mental-MarcoRg06#1]
Actividad 1 Mapa Mental 
Nombre: Marco Uriel Rosas Garcia 1BS
[Actividad 1 MAPA MENTAL .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-MarcoRg06/files/9466543/Actividad.1.MAPA.MENTAL.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 18.4% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
